import os, sipconfig, sys

# The name of the SIP build file generated by SIP and used by the build system.
build_file = "TestMath.sbf"

# Get the SIP configuration information.
# Documentation: http://pyqt.sourceforge.net/Docs/sip4/build_system.html
config = sipconfig.Configuration()

# Run SIP to generate the code.
cmd = " ".join([config.sip_bin, "-c", ".", "-b", build_file, "TestMath.sip"])
print("running command " + cmd)
os.system(cmd)

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

# Add the library we are wrapping.
# The name doesn't include any platform specific prefixes or extensions.
makefile.extra_libs = ["sipdemo"]

# Generate the Makefile itself.
makefile.generate()